version: "3.11"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: super-duper-umbrella-web
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    command: >-
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
