version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./app.db:/app/app.db
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
